export const masterApiPaths = {
  getAnnounceCauses: '/Announce/GetAnnounceCauses',
  getOccasionMaster: '/Announce/GetOccasionMaster',
  getHowToDonateMaster: 'Announce/GetAnnounceRemarkMasterHowToDonate',
  getAnnounceList: '/Announce/GetAnnounceList',
  getAnnounceDetailsById: '/Announce/GetAnnounceDetailsById',
  createAnnounce: '/Announce/CreateAnnounce',
  updateAnnounce: '/Announce/UpdateAnnounce',
  getCitList: '/CIT/GetCITList',
  getCitDetailsById: '/CIT/GetCITById',
  createCit: '/CIT/InsertCIT',
  updateCit: '/CIT/UpdateCIT',
  getCallCategoryList: '/CIT/GetCallCategoryList',
  getCallSubCategoryList: '/CIT/GetCallSubCategoryList',
} as const;
