export const masterApiPaths = {
  searchDonorData: '/master/searchDonorData',
  getAnnounceCauses: '/Announce/GetAnnounceCauses',
  getEventDetails: '/master/getEventDetails',
  getOccasionMaster: '/Announce/GetOccasionMaster',
  getHowToDonateMaster: 'Announce/GetAnnounceRemarkMasterHowToDonate',
  getStatesByCountry: '/master/GetStatesByCountry',
  getDistrictByState: '/master/GetDistrictByState',
  getStateAndDistrictByPinCode: '/master/GetStateAndDistrictByPinCode',
  getPurposeByDataFlag: '/master/GetPurposeByDataFlag',
  getCurrencyByCountry: '/master/GetCurrencyByCountry',
  getYojnaByPurposeAndCurrency: '/master/GetYojnaByPurposeAndCurrency',
  getOperationAmountByQty: '/master/GetOperationAmountBYQty',
  getSalutations: '/master/GetSalutations',
  getDepositBanks: '/master/GetDepositBanks',
  getAnnounceList: '/Announce/GetAnnounceList',
  getAnnounceDetailsById: '/Announce/GetAnnounceDetailsById',
  createAnnounce: '/Announce/CreateAnnounce',
  updateAnnounce: '/Announce/UpdateAnnounce',
  getCitList: '/CIT/GetCITList',
  getCitDetailsById: '/CIT/GetCITById',
  createCit: '/CIT/InsertCIT',
  getCallCategoryList: '/CIT/GetCallCategoryList',
  getCallSubCategoryList: '/CIT/GetCallSubCategoryList',
} as const;